FROM golang:1.23 AS builder
WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o proxy ./proxy

FROM scratch
COPY --from=builder /app/proxy .
CMD ["./proxy"]
