name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install Go
      # https://github.com/actions/setup-go/releases/tag/v5.0.0
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: 'go.mod'
    - run: make test
