name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Install Go
      # https://github.com/actions/setup-go/releases/tag/v5.0.0
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version-file: 'go.mod'
    - run: make test
