name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Create release on Github
        env:
          GH_TOKEN:  ${{ github.token }}
        run: |
          if [[ "${{ github.ref_name }}" == *-rc* ]]; then
            gh --repo "${{ github.repository }}" release create ${{ github.ref_name }} --verify-tag --generate-notes --prerelease
          else
            gh --repo "${{ github.repository }}" release create ${{ github.ref_name }} --verify-tag --generate-notes
          fi
