name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name : Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create release on Github
        env:
          GH_TOKEN:  ${{ github.token }}
        run: |
          if [[ "${{ github.ref_name }}" == *-rc* ]]; then
            gh --repo "${{ github.repository }}" release create ${{ github.ref_name }} --verify-tag --generate-notes --prerelease
          else
            gh --repo "${{ github.repository }}" release create ${{ github.ref_name }} --verify-tag --generate-notes
          fi
